language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"

sudo: false

install:
  - pip install coveralls dotobject

script: coverage run --source redisworks setup.py test

after_success:
  - coveralls